# Generated by Django 4.1.4 on 2023-04-30 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('ship', '0002_alter_order_shipping_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='main.app'),
            preserve_default=False,
        ),
    ]
