# Generated by Django 4.1.4 on 2023-05-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_affiliate_templateshare_affiliate_visit_affiliate'),
        ('ship', '0005_affiliate_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='main.affiliate'),
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
    ]
