# Generated by Django 4.1.4 on 2023-05-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0007_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
