# Generated by Django 4.1.4 on 2023-05-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0008_warehouse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
