# Generated by Django 4.1.4 on 2023-05-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0009_warehouse_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'cod'), ('card', 'card')], default='cod', max_length=100),
        ),
    ]
