# Generated by Django 4.1.4 on 2023-05-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0012_alter_channel_type_alter_constantchannel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
