# Generated by Django 4.1.4 on 2023-05-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0014_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'cod'), ('card', 'card')], default='card', max_length=100),
        ),
    ]
