# Generated by Django 4.1.4 on 2023-06-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0015_alter_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
