# Generated by Django 4.1.4 on 2023-03-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='only_admins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='only_admins',
            field=models.BooleanField(default=False),
        ),
    ]
