# Generated by Django 4.1.4 on 2023-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_section_only_admins_theme_only_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(default='nuuul'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='content',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
