# Generated by Django 4.1.4 on 2023-03-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_section_content_theme_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='preview_content',
            field=models.TextField(default='nukk'),
            preserve_default=False,
        ),
    ]
