# Generated by Django 4.1.4 on 2022-12-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.CharField(default='1afeb635-cc48-4fe5-9aab-7c7fee4e6d83', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='formsrecord',
            name='name',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=85),
        ),
    ]
