# Generated by Django 4.1.4 on 2022-12-30 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('custom', 'Custom'), ('normal', 'Normal')], max_length=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.domain'),
        ),
    ]
