# Generated by Django 4.1.4 on 2022-12-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_app_app_id_alter_formsrecord_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.CharField(default='9c041ae7-8d30-4a71-ae46-e12df7970fbf', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='formsrecord',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formsrecord',
            name='city',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='formsrecord',
            name='phone_number',
            field=models.CharField(max_length=85),
        ),
    ]
