# Generated by Django 4.1.4 on 2023-02-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_feature_description_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='app',
        ),
        migrations.AddField(
            model_name='template',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='main.domain'),
            preserve_default=False,
        ),
    ]
