# Generated by Django 4.1.4 on 2022-12-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_domain_alter_app_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain',
            new_name='name',
        ),
    ]
