# Generated by Django 4.1.4 on 2023-02-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_domain_app_template_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
    ]
