# Generated by Django 4.1.4 on 2023-05-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lead_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincity',
            name='aymakan',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincity',
            name='jonex',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincity',
            name='smsa',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
