# Generated by Django 4.1.4 on 2022-12-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_app_app_id_alter_formsrecord_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.CharField(default='a71dda54-6ed5-4b9d-a135-a6e1aec45ec1', max_length=200, unique=True),
        ),
    ]
