# Generated by Django 4.1.4 on 2023-05-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_maincity_aymakan_maincity_jonex_maincity_smsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincity',
            name='aramex',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
