# Generated by Django 4.1.4 on 2023-02-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_template_is_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='main.domain'),
        ),
    ]
