# Generated by Django 4.1.4 on 2022-12-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_app_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.CharField(default='38759c0f-84e1-4cf2-a7fc-94dbcf9ec165', max_length=200, unique=True),
        ),
    ]
