# Generated by Django 4.1.4 on 2022-12-21 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_app_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
