# Generated by Django 4.1.4 on 2022-12-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_app_domain_domain_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='customer_website',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
