# Generated by Django 4.1.4 on 2023-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_template_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='template',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
