# Generated by Django 4.1.4 on 2022-12-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_app_customer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='record_id',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
