# Generated by Django 4.1.4 on 2023-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_app_auto_ship_cc_app_auto_ship_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='card_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='template',
            name='cod_payment',
            field=models.BooleanField(default=True),
        ),
    ]
