# Generated by Django 4.1.4 on 2022-12-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
