# Generated by Django 4.1.4 on 2022-12-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_domain_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='main.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_products', to='main.template')),
            ],
        ),
    ]
