# Generated by Django 4.1.4 on 2023-02-10 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_template_logo_alter_template_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_templates', to='main.template'),
        ),
    ]
