# Generated by Django 4.1.4 on 2022-12-31 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_templateproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsrecord',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forms_templates', to='main.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=85)),
                ('region', models.CharField(max_length=85)),
                ('location', models.CharField(max_length=222)),
                ('country', models.CharField(max_length=85)),
                ('ip_address', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='main.template')),
            ],
        ),
    ]
