# Generated by Django 4.1.4 on 2023-06-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_template_preview_image_alter_template_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
