# Generated by Django 4.1.4 on 2022-12-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_formsrecord_product_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='app',
        ),
        migrations.AddField(
            model_name='app',
            name='next_template',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TemplateProduct',
        ),
    ]
