# Generated by Django 4.1.4 on 2023-02-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_template_options_template_next_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formsrecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('progress', 'progress'), ('indelivery', 'indelivery'), ('delivered', 'delivered'), ('undelivered', 'undelivered')], default='pending', max_length=100),
        ),
    ]
