# Generated by Django 4.1.4 on 2022-12-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_app_app_next_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='json_object',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
