# Generated by Django 4.1.4 on 2022-12-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_visit_json_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='json_object',
            field=models.TextField(),
        ),
    ]
