# Generated by Django 4.1.4 on 2023-02-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_template_total_redirect_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=85)),
                ('city', models.CharField(max_length=85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='feature_text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
