# Generated by Django 4.1.4 on 2023-01-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_visit_duration_alter_visit_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsrecord',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
