# Generated by Django 4.1.4 on 2023-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_templateshare_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='secondary_color',
            field=models.CharField(blank=True, default='#FBF4EA', max_length=20, null=True),
        ),
    ]
