# Generated by Django 4.1.4 on 2023-01-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_formsrecord_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
