# Generated by Django 4.1.4 on 2023-02-22 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_template_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateshare',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='main.product'),
            preserve_default=False,
        ),
    ]
