# Generated by Django 4.1.4 on 2023-02-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_template_main_rating_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='extra_js',
            field=models.TextField(blank=True, null=True),
        ),
    ]
