# Generated by Django 4.1.4 on 2023-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_template_extra_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='css',
            field=models.TextField(default='<h1>helli</h1>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='html',
            field=models.TextField(default='<h1>helli</h1>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='js',
            field=models.TextField(default='<h1>helli</h1>'),
            preserve_default=False,
        ),
    ]
