# Generated by Django 4.1.4 on 2023-03-10 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_section_content_theme_content'),
        ('main', '0020_template_css_template_html_template_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(default=1, max_length=85),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='themes.theme'),
        ),
    ]
