# Generated by Django 4.1.4 on 2023-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_template_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='js',
            field=models.TextField(blank=True, null=True),
        ),
    ]
