# Generated by Django 4.1.4 on 2023-03-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_template_css_alter_template_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='project_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
