# Generated by Django 4.1.4 on 2023-03-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_domain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateshare',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='main.product'),
        ),
    ]
