# Generated by Django 4.1.4 on 2023-03-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_templateshare_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateshare',
            name='city',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
