# Generated by Django 4.1.4 on 2023-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_template_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='business_name',
        ),
        migrations.AddField(
            model_name='app',
            name='business_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
